workflows:
  ios-build:
    name: iOS Build (AltStore)

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build iOS app (no IPA export)
        script: |
          flutter build ios --release

    artifacts:
      - build/ios/iphoneos/*.app